#!/bin/bash
mkdir -p ~/.docker/swarm
 echo 'function vaultssh() { echo ${1}; tmpfile=$(mktemp /tmp/secret.XXX); chmod 600 /tmp/secret.XXX; vault read -field=private_key -format=raw secret/resources/qubeship/qa > /tmp/secret.XXX; ssh -i /tmp/secret.XXX root@${1}; };' >> ~/.bash_profile
echo 'function vaultscpto() { echo ${1}; tmpfile=$(mktemp /tmp/secret.XXX); chmod 600 /tmp/secret.XXX; vault read -field=private_key -format=raw secret/resources/qubeship/qa > /tmp/secret.XXX; scp -i /tmp/secret.XXX $1 root@${2}; };' >> ~/.bash_profile
echo 'function vaultscpfrom() { echo ${1}; tmpfile=$(mktemp /tmp/secret.XXX); chmod 600 /tmp/secret.XXX; vault read -field=private_key -format=raw secret/resources/qubeship/qa > /tmp/secret.XXX; scp -i /tmp/secret.XXX root@${1} $2; };' >> ~/.bash_profile
echo 'function install_certs() { cd ~/.docker/swarm; vaultscpfrom node1.qa.qubeship.io:/root/client_cert_bundle.tar.gz .; tar xvzf client_cert_bundle.tar.gz; };' >> ~/.bash_profile
echo 'function swarm_machine() { echo export DOCKER_HOST=tcp://$( dig node1.qa.qubeship.io +short | tail -1 ):2376; echo export DOCKER_TLS_VERIFY=1; echo export DOCKER_CERT_PATH=~/.docker/swarm; };' >> ~/.bash_profile

source ~/.bash_profile
