#!/bin/bash

cluster_name=${1:-qube-1}
project_name=${2:-qubeship}
echo "switching to $cluster_name $project_name"
if [ "$project_name" == "--local" ]; then
	kubectl config use-context $cluster_name
else
	gcloud config set project $project_name
	gcloud config set container/cluster $cluster_name
	gcloud container clusters get-credentials $cluster_name
fi