apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  namespace: test
#  labels:
#    app: my-nginx
spec:
  ports:
  - port: 80 
    targetPort: 80 
    name: port0
  selector:
    app: my-nginx
#  type: ClusterIP
  type: NodePort
  sessionAffinity: None
